### ISSUE TITLE
Make a better pitch shifter for percussive sounds

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#1004]
To reproduce:

- Create a block with AudioIn -> PitchShifter -> AudioOut
- Send a pitched percussive sound to the AudioIn

Expected:

- Only pitch shifting is heard

Actual:

- Pitch shifting is heard with a short delay

Notes:

- I don't think this can be fixed with only minor changes to the PitchShifter. We will either need to replace the implementation completely, or create a new PitchShifter module based on a different technique, e.g. FFT (of course this will be more CPU intensive) in which case it may be interesting to create a more advanced module, e.g. SpectralShifter, which could be part of a "spectral" module bundle.

**Comment by jamiebullock** [comment]
Here's an example Spectral shifter

[fft-pitchshifter.zip](https://github.com/BirminghamConservatoire/IntegraLive/files/56519/fft-pitchshifter.zip)

**Comment by elmiquito** [comment]
If nobody else is building it I'd be happy to create a nice polyphonic harmoniser using fft-pitchshifter as a starting point. It would be useful to have a widget displaying a string with MIDI note names (i.e. A1, G#5, Ab, etc.). Is it something one could do using a *very long* list of allowed values for a number box widget or not?

**Comment by elmiquito** [comment]
A first stab at a 4-voice Harmoniser. 
[QuadHarmoniser.module.zip](https://github.com/BirminghamConservatoire/IntegraLive/files/68717/QuadHarmoniser.module.zip)

**Comment by elmiquito** [comment]
Fixed in commit 58e1cc5
