### ISSUE TITLE
Improve workflow for Module Creator

### ISSUE THREAD

**Issue by elmiquito** [BirminghamConservatoire/IntegraLive#1006]
Refer to open issues #866, #828, #832, plus a request for a Duplicate Endpoint button to the Endpoints view of Module Creator. Is the task hard? I saw that Leighton was the assignee on #866, anyone else that could do the job? This would be a good starting point to help standardise widget size and layout across the module library.

**Comment by jamiebullock** [comment]
#866 probably won't be too difficult so I've assigned it to myself to take a look. The others aren't really feasible with our current resources (I'm the only person who could do them and they're all non-trivial). I agree these things would be nice to have, butI think there are many other tasks that deserve a higher priority at this point.

**Comment by elmiquito** [comment]
Agreed, it makes sense to close only #866
