### ISSUE TITLE
Website problems

### ISSUE THREAD

**Issue by mxmilkiib** [BirminghamConservatoire/IntegraLive#1022]
http://integra.io/ doesn't relate to the software and http://integra.io/portfolio/integra-live/ is 404

**Comment by NiccoloGranieri** [comment]
Hi @mxmilkb, thanks for letting us know! We recently migrated the website to another server and this might have been as issue that arose in the process.

http://integra.io is the website of the research lab that originally created integra live, and the page of the software is now accessible from http://integra.io/integralive/.

Let me know if you encounter any other problems, thanks!
