### ISSUE TITLE
Integra Live won't launch on macOs Big Sur 

### ISSUE THREAD

**Issue by elmiquito** [BirminghamConservatoire/IntegraLive#1026]
Pablo Furman at San José State University reported last week that IL won't launch on Macs running macOs Big Sur. A message comes up requesting an updated  version. Is there an easy way to fix this?
I'm still running on High Sierra and students here use mostly Catalina without problems, but I'll try to reproduce on an extra machine if I can get hold of one.

**Comment by Richc** [comment]
Integra live does launch on Big Sur, if pops up an unidentified developer which blocks it from opening but you can ok it in system preferences security.

R

**Comment by elmiquito** [comment]
Many thanks @Richc, I've passed this one to Pablo. So I assume you can also use the standard ctrl-click Open to access the Open dialog box, instead of double-clicking the application, so that macOS security measures are bypassed?
