### ISSUE TITLE
Fix text entry on controls

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#104]
---Migrated from Sifter - Sifter issue 110---
When entering numbers via the keyboard some controls lose focus when you click away, others require 'return' to be pressed before the text entry box loses focus

**Comment by NiccoloGranieri** [comment]
In Integra 1.7.1 no control seems to be affected by this bug. All the text entry controls set themselves to the input value both by hitting return after typing the value and by clicking away, there is no lost of focus and no lost values. 

The only thing I could notice is that on sliders, if a value is set and then with the mouse we directly click on another slider to set it too, the values will remain in a "setting" state until we effectively click away, at that moment they will be se all together.
