### ISSUE TITLE
Create a set of test projects for functional tests

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#387]
---Migrated from Sifter - Sifter issue 405---
We need a set of projects for testing purposes this includes:

- module regression test
- project size test
- performance tests

**Comment by jamiebullock** [comment]
@balandinodidonato We need a set of projects that implement stress tests: http://en.wikipedia.org/wiki/Stress_testing_(software) and regression tests: http://en.wikipedia.org/wiki/Regression_testing

The reason for this is that we:

- Need to know when we change anything, whether the changes break anything (regression tests will tell us this)
- What are the limits of the software (stress tests will do this)

Stress tests will also help uncover bugs.

**Comment by balandinodidonato** [comment]
@jamiebullock this is a quite busy period, but we can definitely have a chat about it and I would be happy to do it ASAP.

**Comment by jamiebullock** [comment]
This isn't urgent. It can wait until we are less busy

**Comment by balandinodidonato** [comment]
#978

**Comment by NiccoloGranieri** [comment]
Closed in #978
