### ISSUE TITLE
Audio sounds terrible (crackly) when using Apogee One interface

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#583]
---Migrated from Sifter - Sifter issue 601---
To reproduce:

- connect up Apogee One interface via USB
- select ONE for input and output in preferences
- connect audioin to stereoaudioout

Expected behaviour:

- it sounds OK

Actual behaviour:

- it sounds rubbish.

**Comment by jamiebullock** [comment]
@balandinodidonato Please test this with the Apogee one in the lab

**Comment by balandinodidonato** [comment]
IL1.7 sounds good now.
