### ISSUE TITLE
Pitch Shifter:  "speedchange fx" rotating windowSize knob

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#614]
---Migrated from Sifter - Sifter issue 632---
to reproduce :

- drag an OctoSound and a Pitch Shifter in the project, connect them, choose a soundfile, and press play

- rotate the Pitch knob ( for example, just to -720 value )

- rotate the windowSize knob (for example, just to 1.100 value )

...it seems like the "file speed-reading" decreases, instead of stay stationary (thing that happens when windowSize is setted on the   minVal  , 0.001 )..  

i don't know if it was a intentional choice..

but probably, people from Pitch Shifter could expect to obtain just a 'pitch change' without a 'time change'

**Comment by balandinodidonato** [comment]
Hi @jamiebullock I had a look into it but didn't really know where the bug  could be. If you prefer I can implement a simple pitch shifter. What do you think?

**Comment by jamiebullock** [comment]
I'm closing this as I don't think it's really possible to fix without changing the interface (removing windowSize) and I don't think removing windowSize is really productive.

**Comment by balandinodidonato** [comment]
you are actually right @jamiebullock.
