### ISSUE TITLE
Incorrect envelope range for parameters of Stereo Granular Synthesiser

### ISSUE THREAD

**Issue by elmiquito** [BirminghamConservatoire/IntegraLive#725]
The envelope ranges in Arrange View for minGrainSize and maxGrainSize of Stereo Granular Synthesiser do not match the ranges in the Module View

**Comment by balandinodidonato** [comment]
@jamiebullock it seems right to me as well. Is it possible to close this issue?

**Comment by jamiebullock** [comment]
Closing as unreproducible. Will re-open if the issue can be demonstrated.
