### ISSUE TITLE
Drag the IntegraLive or Module Creator window in a new "Spaces"

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#773]
IMPORTANT: You can find this bug only on Mac OS.

To reproduce:
  - Open Integra Live.app or Mudule Creator.app
  - Drag the window of Integra Live or Module Creator in a new Spaces

Expected:
  - You can drag the IntegraLive or Module Creator window in a different "Spaces"

Actual:
  - The window remain in the previous "Spaces"

**Comment by jamiebullock** [comment]
I just updated to Adobe AIR 16.0 and the issue seems to now be fixed. The fix will be available in the next build
