### ISSUE TITLE
Is impossible to reopen a saved project

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#785]
*Is happened three time today.*

**To reproduce**
- Develope a bit complex project with four track with each one a soundFiler, quadPanner and quadAudioOut, and une track contain a QuadGranularSynthesizer.
- Create some envelope for each block 
- Push the Play button of IntegraLive
- Hear the sound and check that all is going be all right
- Push the pause button of IntegraLive
- Save the project
- Open the saved project

**Expected**
- The project will be open normally

**Actual**
- You can't open the project and the follow error message appears:

--------------------------------------------------------
 Cannot load project:

File was saved in a more recent version of Integra, and cannot be loaded in this version.

Please upgrade to the latest version of Integra.

-----------------------------------------------------------
![screen shot 2013-07-18 at 17 10 32](https://f.cloud.github.com/assets/4600922/820482/d9749eb0-efc5-11e2-96d5-ff6874acd667.png)

**Comment by jamiebullock** [comment]
Closed as fixed in 1.6.4
