### ISSUE TITLE
Factor out use of hcs/sys_gui external

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#850]
The following abstractions use the `hcs/sys_gui` external:

- quadSoundfilePlayerRecorder~.pd
- octoSoundfilePlayerRecorder~.pd
- esaSoundfilePlayerRecorder~.pd
- stereoSoundfilePlayerRecorder~.pd
- monoSoundfilePlayerRecorder~.pd

`hcs/sys_gui` is an external and it is used in the above abstractions in the `sf_read` subpatch in order to delete previous audio files. 

We need to factor out `hcs/sys_gui` since it uses Tcl messaging to access the local filesystem. Tcl will not be available when we switch to using libPd so these abstractions will no longer work.

An initial inspection of the above abstractions suggests that it may be possible to simply remove the "delete" functionality on the basis that `soundfiler` overwrites files anyway.

**Comment by balandinodidonato** [comment]
@jamiebullock this module seems working without the `hcs/sys_gui` abstraction in the release 1.7 branch. Could you check it please?
