### ISSUE TITLE
Ring Modulator second input does not work

### ISSUE THREAD

**Issue by jrdooley** [BirminghamConservatoire/IntegraLive#919]
The Ring Modulator allows the user to modulate an incoming signal (in1) with either a sine wave, a square wave or another incoming source (in2). Currently, the module does not allow the user to modulate in1 with in2.

**Comment by balandinodidonato** [comment]
@jrdooley not is seems working. could you confirm that you are able to modulate the incoming signal (in1) through a second signal (in 2)?
