### ISSUE TITLE
Add support for multiple MIDI devices

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#929]
We should provide a way to support multiple MIDI devices in Integra Live.

This has been requested a number of times by users, see: http://integralive.org/forum/discussion/682/multiple-midi-inputs-and-outputs

**Comment by balandinodidonato** [comment]
@jamiebullock I guess it has been implemented in the 1.7 release. isn't it?

**Comment by jamiebullock** [comment]
@balandinodidonato yes, done!
