### ISSUE TITLE
1.6 crashes when loading projects saved in 1.7

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#947]
To reproduce:

- Save a project in 1.7
- Try to open it in 1.6

Exepected:

- An alert is displayed stating the file cannot be opened because it was saved in a more recent version of the software (we don't support forwards compatibility in Integra Live)

Actual:

- The software crashes

**Comment by jamiebullock** [comment]
This should be considered a 1.7 (or later) bug, as there is no sense in fixing it in 1.6 which is about to be superseded, but should be fixed for 1.7 or later

**Comment by NiccoloGranieri** [comment]
Wasn't able to reproduce the crash between IL 1.7.1 and IL 1.6.4. The correct alert popped up.

**Comment by jamiebullock** [comment]
@NiccoloGranieri good! This may have been fixed as a side effect of fixing #993
