### ISSUE TITLE
MIDI Routing - IntegraLive->External application

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#950]
Firstly, I don't know if it is a bug or if "IntegraLive 1.6" is not allowed to do it.

However, I wanted to route the value from IntegraLive to another application such as PureData or Max/MSP via MIDI, but I didn't get any good results.

TO REPRODUCE:
- drag and drop the "SoundfileLoop" block from the "Block Library" to the track 1
- create a routing between the value "position" and "cc10" of "MIDI1"

EXPECTED:
- it is possible to receive the "soundLevel" value rescaled into MIDI values by the external application.

ACTUAL:
- it is not possible

N.B. 
The same process has been reproduced in the following ways:
- by using different modules
- by changing "cc" values
- by using different network bus
- by using pd-exteden and Max/MSP

The MIDI network between the external application and IntegraLive, it is perfectly working. 
It has been tested by trying to send MIDI messages from the same application to IntegraLive.

**Comment by balandinodidonato** [comment]
@jamiebullock

**Comment by jamiebullock** [comment]
I've actually never really thought about this! Is it possible to send MIDI from Max to Pd, for example?

Rather than adding MIDI output support, which seems rather esoteric, I've added a new issue for OSC support, which would solve the problem you describe in a more suitable way: #961
