### ISSUE TITLE
Endpoint name

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#952]
Important: I do not know if the users are allowed or not to do it for specific reasons.

To reproduce:
- Create a new module by using the Module Creator
- Add a widget
- Rename the Endpoint Name without use letter or number, for instance: . , < > / ? ! @ £ $ % ^... etc
- Rename the Endpoint Name by using numbers only

Expected:
- The user rename an endpoint without use letters and numbers or by using different sign as well.
- The user rename an endpoint by using numbers only.

Current:
- The user is allowed to rename the Endpoint Name by using letter and numbers only
- The user is not allowed to rename the Endpoint Name by using numbers

**Comment by balandinodidonato** [comment]
@jamiebullock

**Comment by jamiebullock** [comment]
You are right, it is by design that numeric-only endpoint names are not allowed. This is simply because we want to encourage people to give their endpoints meaningful names.
