### ISSUE TITLE
Building Process not working - Java issue

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#956]
The building process for the release 1.7 si not working properly or I did some mistakes.

System: Mac OSX Yosemite 10.10.1 (14B25)

Balandinos-MacBook-Pro:macosx balandinodidonato$ make release
make -C ../../GUI/src app
sed  -e 's|x.x.x.xxxx|1.7.0.3303|g' -e 's|x.x.x|1.7.0|g' IntegraLive-app.xml.in > IntegraLive-app.xml
/Library/Frameworks/flex_sdk_4/bin/amxmlc -compiler.verbose-stacktraces -load-config app-config.xml IntegraLive.mxml
No Java runtime present, requesting install.
make[1]: *** [IntegraLive.swf] Error 1
make: *** [gui] Error 2

As it is shown from the terminal print-out to, on the 3rd line from the bottom, the system is asking to install Java runtime even if it has already been install.

I did try to reinstall it a couple of times and then repeat the building process but the resutl is the same.

**Comment by jamiebullock** [comment]
Hmm... what is the result from the command line of typing "java -version". It should display something like this:

```
jamie$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by balandinodidonato** [comment]
Hi Jamie I just updated My ave version and I tried to build Integra again. Here the terminal output:

Balandino:macosx balandinodidonato$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
Balandino:macosx balandinodidonato$ make release
make -C ../../GUI/src app
sed  -e 's|x.x.x.xxxx|1.7.0.3304|g' -e 's|x.x.x|1.7.0|g' IntegraLive-app.xml.in > IntegraLive-app.xml
/Volumes/Macintosh\ HD/Users/balandinodidonato/SDKs/Flex/bin/amxmlc -compiler.verbose-stacktraces -load-config app-config.xml IntegraLive.mxml
Loading configuration file /Users/balandinodidonato/git-repositories/IntegraLive/GUI/src/app-config.xml
Apache Flex Compiler (mxmlc)
Version 4.13.0 build 20140701
Copyright 2014 The Apache Software Foundation.

/Users/balandinodidonato/git-repositories/IntegraLive/GUI/src/app-config.xml(138): Error: unable to open '/Users/balandinodidonato/IntegraLive/GUI/src/../libs/FlexUnit.swc'

      </library-path>

make[1]: *** [IntegraLive.swf] Error 1
make: *** [gui] Error 2

**Comment by jamiebullock** [comment]
Right. What is the output of `ls -al /Users/balandinodidonato/IntegraLive/GUI/src/../libs/` from a Terminal prompt?

**Comment by balandinodidonato** [comment]
Balandino:macosx balandinodidonato$ ls -al /Users/balandinodidonato/IntegraLive/GUI/src/../libs/
ls: /Users/balandinodidonato/IntegraLive/GUI/src/../libs/: No such file or directory

**Comment by jamiebullock** [comment]
OK, it seems like you've somehow deleted your libs/ directory from IntegraLive/GUI!

If you go into git Tower, or type `git status` from the command line, it should that libs is missing.

You should be able to restore the files from Tower

**Comment by balandinodidonato** [comment]
mmmm it sounds weird:

Balandino:IntegraLive balandinodidonato$ git status
On branch release-1.7
Your branch is up-to-date with 'origin/release-1.7'.

nothing to commit, working directory clean

**Comment by jamiebullock** [comment]
That *is* weird. There is definitely a "libs" in the origin repository: https://github.com/BirminghamConservatoire/IntegraLive/tree/release-1.7/GUI/libs

What does `ls -al /Users/balandinodidonato/IntegraLive/GUI` give you?

**Comment by balandinodidonato** [comment]
Balandino:IntegraLive balandinodidonato$ ls -al /Users/balandinodidonato/IntegraLive/GUI
ls: /Users/balandinodidonato/IntegraLive/GUI: No such file or directory

**Comment by balandinodidonato** [comment]
I'm sorry @jamiebullock I was pointing at the wrong path.

Balandino:IntegraLive balandinodidonato$ ls -al /Users/balandinodidonato/git-repositories/IntegraLive/GUI/src/../libs/
total 1736
drwxr-xr-x  4 balandinodidonato  staff     136  4 Dec 09:22 .
drwxr-xr-x  7 balandinodidonato  staff     238 25 Mar 11:38 ..
-rw-r--r--  1 balandinodidonato  staff  868307  4 Dec 09:22 FlexUnit.swc
-rw-r--r--  1 balandinodidonato  staff   16436  4 Dec 09:22 fzip.swc
Balandino:IntegraLive balandinodidonato$

**Comment by balandinodidonato** [comment]
Balandino:IntegraLive balandinodidonato$ ls -al /Users/balandinodidonato/git-repositories/IntegraLive/GUI
total 24
drwxr-xr-x   7 balandinodidonato  staff   238 25 Mar 11:38 .
drwxr-xr-x@ 19 balandinodidonato  staff   646 25 Mar 11:38 ..
-rw-r--r--   1 balandinodidonato  staff  2331 25 Mar 11:38 .actionScriptProperties
-rw-r--r--   1 balandinodidonato  staff   202 25 Mar 11:38 .flexProperties
-rw-r--r--   1 balandinodidonato  staff  1044 25 Mar 11:38 .project
drwxr-xr-x   4 balandinodidonato  staff   136  4 Dec 09:22 libs
drwxr-xr-x  20 balandinodidonato  staff   680 25 Mar 11:38 src

**Comment by balandinodidonato** [comment]
Hi @jamiebullock , I cleaned my repository and cloned it again.

I trying the build process again and it seems that my java version (that last one) seems not be the correct one. which one should be?

Balandino:macosx balandinodidonato$ make release
make -C ../../GUI/src app
sed  -e 's|x.x.x.xxxx|1.7.0.3304|g' -e 's|x.x.x|1.7.0|g' IntegraLive-app.xml.in > IntegraLive-app.xml
mkdir BlockLibrary
cp ../../blocks/* BlockLibrary/
/Library/Frameworks/flex_sdk_4/bin/amxmlc -compiler.verbose-stacktraces -load-config app-config.xml IntegraLive.mxml
Error: This Java instance does not support a 32-bit JVM.
Please install the desired version.
make[1]: *** [IntegraLive.swf] Error 1
make: *** [gui] Error 2
Balandino:macosx balandinodidonato$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
Balandino:macosx balandinodidonato$

**Comment by jamiebullock** [comment]
Ah, right. This is where we run into problems with using Adobe Flex. Unfortunately, you need to make a small "hack" to the Flex distribution to fix this. See: http://stackoverflow.com/a/13302428/172218

So you need to edit /Library/Frameworks/flex_sdk_4/bin/mxmlc and comment out those lines
