### ISSUE TITLE
Ring modulator add distortion to distorted files only

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#959]
To reproduce:
- Modulate a distorted sound using the ring modulator

Expected:
- the modulation doesn't add any distortion

Actual:
- the sound is even more distorted (it seems an aliasing problem)

**Comment by jamiebullock** [comment]
I'm a bit confused by this. You have a Soundfiler going into a RingModulator, is that correct?

The RingModulator performs the same operation regardless of the input. Do you get distortion if the input is a sine wave?

**Comment by balandinodidonato** [comment]
It does not happen with a sine wave. Yet, it happened with rich sounds, in spectral terms.

**Comment by jamiebullock** [comment]
Thinking about it, of course the output of a ring modulator is dependent on the frequency content of the input. For each of N sinusoidal frequency components in the input, you are getting outputs of `Cf[n] + Mf` and `Cf[n] - Mf` where Cf[n] is the frequency of the nth input sine and Mf is the frequency of the modulator sine. So if you have a distorted input you are probably introducing high frequency components that will cause aliasing. It might be possible to *reduce* this by upsampling the inputs, processing, filtering and downsampling in the implementation of RingModulator.

**Comment by jamiebullock** [comment]
@balandinodidonato are you comfortable implementing the above fix? If so, I will assign this to you.

**Comment by balandinodidonato** [comment]
Yes Jamie, I will do it in the near future.
