### ISSUE TITLE
soundfiler midi command

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#960]
To reproduce
- Map the play command with the play button of a Korg nanoKONTROLLER 2

Expected:
- when the user press and then release the play the butto start to be reproduced

Actual:
- when the user release the button, the sounddfiler pause file reproduction

**Comment by jamiebullock** [comment]
Can you look at the MIDI monitor (top right) in a Integra Live and confirm whether the nanokontrol is acting as a toggle (press once sends "1", press again sends "0") or as simple button (press sends "1", release sends "0"). I suspect it is the latter, which would explain the behaviour you're seeing. If so, the solution is to use the Scaling in the Routing view to map both 0 and 1 to 1 and use the "stop" button on the nanokontrol to stop playback by scaling it's output to zero.

**Comment by balandinodidonato** [comment]
Yes. I realised this this morning working at Benjamin's piece. This problem may be fixed in following your solution. I will implement it soon.

**Comment by jamiebullock** [comment]
I'm closing this as it doesn't really seem to be a bug in the software, but rather a mismapping between the controller and software. Will reopen if you think there is a genuine bug.
