### ISSUE TITLE
Soundcard setting

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#965]
To Reproduce:
- open Integra Live 1.7.0
- open preference pannel
- select an M-Audio Fast Track Pro as audio input
- select an M-Audio Fast Track Pro as audio output

Expected
- the audio input and audio output is set on M-Audio Fast Track Pro

Actual
- Integra Live doesn't allow to set it up.

NB: it is perfectly possible on Integra Live 1.6.4.3300

**Comment by jamiebullock** [comment]
Please supply Fast-track pro for testing.

**Comment by balandinodidonato** [comment]
I will definitely supply it.

I did a second test and I can confirm the issue.

**Comment by jamiebullock** [comment]
Also, would you mind checking the logs to see if there is anything suspicious in there. These can be found in `~/Library/Preferences/org.integralive.IntegraLive/Local Store/runtime logs`

You obviously need the latest directory corresponding to the session where a problem occurred.

You could just upload the logs somewhere and post a link.

**Comment by balandinodidonato** [comment]
[Here](https://www.dropbox.com/s/ujrkwa59iu3ybh7/integraLog.zip?dl=0) the gui and server log.

**Comment by NiccoloGranieri** [comment]
Issue solved in 1.7.1.3310
