### ISSUE TITLE
Test in Integra Live doesn't work in Module Creator

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#972]
To reproduce:
- Edit a module
- Select "Test in Integra Live"

Behaviour:
- Integra Live opens but hangs at "Installing module..."

**Comment by balandinodidonato** [comment]
Hi @jamiebullock I still have the same problem.

**Comment by jamiebullock** [comment]
Can you try this build: http://integralive.org/incoming/Module%20Creator%201.7.0.3307.zip

It might be that it's not fully rebuilding on your laptop. Perhaps try `sudo clean && make release && make creator`

**Comment by balandinodidonato** [comment]
It was my fault. I didn't notice that the command `make clean` is not working anymore.

gg1107i1-dm0006:~ balandinodidonato$ cd /Users/balandinodidonato/git-repositories/IntegraLive/IntegraLive/macosx/
gg1107i1-dm0006:macosx balandinodidonato$ make clean
rm -rf server
make -C ../../GUI/src clean
rm -rf pd-0.43-3.mac.tar.gz pd-0.43-3.app
rm: pd-0.43-3.app/Contents/Info.plist: Permission denied
rm: pd-0.43-3.app/Contents/MacOS: Permission denied
rm: pd-0.43-3.app/Contents/PkgInfo: Permission denied
rm: pd-0.43-3.app/Contents/Resources/asio: Permission denied
rm: pd-0.43-3.app/Contents/Resources/autogen.sh: Permission denied
rm: pd-0.43-3.app/Contents/Resources/bin: Permission denied
rm: pd-0.43-3.app/Contents/Resources/configure.ac: Permission denied
rm: pd-0.43-3.app/Contents/Resources/doc: Permission denied
rm: pd-0.43-3.app/Contents/Resources/extra: Permission denied
rm: pd-0.43-3.app/Contents/Resources/INSTALL.txt: Permission denied
rm: pd-0.43-3.app/Contents/Resources/LICENSE.txt: Permission denied
rm: pd-0.43-3.app/Contents/Resources/m4: Permission denied
rm: pd-0.43-3.app/Contents/Resources/Makefile.am: Permission denied
rm: pd-0.43-3.app/Contents/Resources/man: Permission denied
rm: pd-0.43-3.app/Contents/Resources/obj: Permission denied
rm: pd-0.43-3.app/Contents/Resources/pd-file.icns: Permission denied
rm: pd-0.43-3.app/Contents/Resources/pd.icns: Permission denied
rm: pd-0.43-3.app/Contents/Resources/pd.pc.in: Permission denied
rm: pd-0.43-3.app/Contents/Resources/Pd.rsrc: Permission denied
rm: pd-0.43-3.app/Contents/Resources/po: Permission denied
rm: pd-0.43-3.app/Contents/Resources/portaudio: Permission denied
rm: pd-0.43-3.app/Contents/Resources/portmidi: Permission denied
rm: pd-0.43-3.app/Contents/Resources/README.txt: Permission denied
rm: pd-0.43-3.app/Contents/Resources/Scripts: Permission denied
rm: pd-0.43-3.app/Contents/Resources/src: Permission denied
rm: pd-0.43-3.app/Contents/Resources/tcl: Permission denied
rm: pd-0.43-3.app/Contents/Resources: Permission denied
rm: pd-0.43-3.app/Contents/version.plist: Permission denied
rm: pd-0.43-3.app/Contents: Permission denied
rm: pd-0.43-3.app: Directory not empty
make: *** [host-clean] Error 1
