### ISSUE TITLE
It is not possible to get MIDI messages through script

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#974]
Integra Live version: 1.7
OS: OS X Yosemite 10.10.3

To reproduce
- connect a midi device
- import a soundfiler
- create a script which involve MIDI messages from from the MIDI device
- create a routing which trigger the script

Expected
- I can see the MIDI value in the info pannel

Actual
- it is not possible to get MIDI values through scripting.

![screen shot 2015-04-30 at 14 25 09 2](https://cloud.githubusercontent.com/assets/4600922/7413571/ce1700dc-ef44-11e4-8f51-43915827a54c.png)

**Comment by jamiebullock** [comment]
The reason for this is that the way MIDI is handled in IL has completely changed in 1.7.

This isn't really a bug, it's an enhancement, but it entails an interface change that unfortunately will break aspects of people's projects if they are routing MIDI or accessing MIDI in script. 

We need some good communication and documentation around this, so I've raised a new issue: #975 

In your specific case, you should be able to access the MIDI value using `MidiControlInput1.value`
