### ISSUE TITLE
Create a module regression test

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#978]
Create a project in 1.6 with an instance of every single module and call it Regression-1.6

Do the same for 1.7 and call it Regression-1.7

We can use these to test what has changed between versions

**Comment by balandinodidonato** [comment]
# Regression test report:#

## x1 Mixer##
The Embedded version of the 4x1 Mixer module (updated Mon Aug 12 2013) in the project1_6_a_g has been upgraded to the **Latest Official version** (updated Mon Aug 18 2014)
### Summary of Changes: ###
- Implementation changed

---
## ￼Gate##
The Embedded version of the Gate module (updated Fri Sep 13 2013) in the project 1_6_a_ghas been upgraded to the **Latest Official version** (updated Sat Oct 4 2014)

### Summary of Changes:###

- Added endpoint 'inSidechain' (audio input)
- Added endpoint 'mode' (string)
- Widget layout changed
- Implementation changed

---
## Distortion ##
The Embedded version of the Distortion module (updated Thu Aug 1 2013) in the project1_6_a_g has been upgraded to the **Latest Official version** (updated Tue Jan 20 2015)

### Summary of Changes: ###

- Implementation changed

---
## Harmonic Filter ##
The Embedded version of the Harmonic Filter module (updated Fri Aug 9 2013) in the project1_6_h_m has been upgraded to the **Latest Official version** (updated Thu Jul 31 2014)
### Summary of Changes: ###

- Description changed

---
## Limiter ##
The Embedded version of the Limiter module (updated Thu Sep 12 2013) in the project1_6_h_m has been upgraded to the **Latest Official version** (updated Thu Jul 3 2014)

### Summary of Changes: ###
- Label changed
- Description changed
- Added endpoint 'ratio' (float)
- Endpoint 'releaseTime' changed (description)
- Endpoint 'makeUp' changed (description)
- Widget layout changed
- Implementation changed

---
## Octo Soundfiler ##
The Embedded version of the Octo Soundfiler module (updated Fri Oct 11 2013) in the project 1_6_o has been upgraded to the **Latest Official version** (updated Mon Sep 29 2014)

### Summary of Changes: ###
- Author changed
- Added endpoint 'outLevel' (float)
- Added endpoint 'inLevel' (float)
- Widget layout changed
- Implementation changed

---
## Stereo Soundfiler ##
The Embedded version of the Stereo Soundfiler module (updated Fri Oct 11 2013) in the project 1_6_p_z has been upgraded to the **Latest Official version** (updated Tue Apr 28 2015)

### Summary of Changes:###
- Added endpoint 'inLevel' (float)
- Added endpoint 'outLevel' (float)
- Widget layout changed
- Implementation changed

---
## Ring Modulator ##
The Embedded version of the Ring Modulator module (updated Mon Jul 8 2013) in the project 1_6_p_z has been upgraded to the **Latest Official version** (updated Wed Jan 21 2015)

### Summary of Changes: ###
- Implementation changed

---
## Quad Soundfiler ##
The Embedded version of the Quad Soundfiler module (updated Fri Oct 11 2013) in the project 1_6_p_z has been upgraded to the **Latest Official version** (updated Mon Sep 29 2014)

### Summary of Changes: ###
- Added endpoint 'inLevel' (float)
- Added endpoint 'outLevel' (float)
- Widget layout changed
- Implementation changed

---
## Soundfiler ##
The Embedded version of the Soundfiler module (updated Fri Oct 11 2013) in the project1_6_p_z has been upgraded to the **Latest Official version** (updated Mon Sep 29 2014)

### Summary of Changes: ###
- Added endpoint 'inLevel' (float)
- Added endpoint 'outLevel' (float)
- Widget layout changed
- Implementation changed

**Comment by jamiebullock** [comment]
Great! Can you create a new directory in the root of the repository, called `testing` and a sub-directory called `regression` and place your tests in there?

**Comment by balandinodidonato** [comment]
Hi @jamiebullock,
do you mean branch for directory?
About the projects, I cannot create a project which include all module in 1.6. When I try to load all modules IL1.6 crashes.

I'm going through the modules which cause the problems.So, to fix the bugs in the 1.7 release.

Thus, in order to go head with the regression test I created more than one projects using IL1.6, and each project will include a group of objects.
In this way it works.

Does it make sense for you?

**Comment by jamiebullock** [comment]
Hi. Yes this approach is fine.

No I don't mean a branch. I mean in the `release-1.7` branch you should just create a directory `testing/regression` add your files there, commit and push your changes.

**Comment by balandinodidonato** [comment]
Please note that in the regression16.integra project, the Brightness Analyser and the Partial analyser are not included because of bugs in IL1.6.
