### ISSUE TITLE
Project created in 1.7 cannot be opened in Integra Live 1.6.

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#979]
From: #978

To reproduce
- Open Integra Live 1.7
- Drag and drop a SoundfileLoop block from block library into a track
- Save the project
- Reopen the project using Integra Live 1.6

Expected
- The project can be opened in Integra Live 1.6

Actual
- Integra Live crashes

**Comment by jamiebullock** [comment]
Thanks for the report. This isn't actually a bug. Whilst we guarantee backwards compatibility (projects saved in *older* versions of the software) we don't support forwards compatibility (projects saved in *newer* versions of the software). We could look into it, but I don't think it's a priority as the majority of users will upgrade their copy of Integra Live when a new release becomes available.
