### ISSUE TITLE
Error: InterfaceDeclaration.EndpointInfo.Endpoint.ControlInfo.StateInfo.Scale.Base

### ISSUE THREAD

**Issue by balandinodidonato** [BirminghamConservatoire/IntegraLive#980]
To reproduce:
- open Integra Live
- insert a soundfiler
- close Integra Live

Expected
- no error in the server log

Actual
- It is possible to find multiple errors such as:

Error [20:00:36 05/07/15] /Users/balandinodidonato/git-repositories/IntegraLive/libIntegra/src/interface_definition_loader.cpp: 422(__FUNCTION__)     unhandled element: InterfaceDeclaration.EndpointInfo.Endpoint.ControlInfo.StateInfo.Scale.Base

First thought by @jamiebullock : It’s possible Scale.Base got deprecated in libIntegra but never got removed from the module creator.

**Comment by jamiebullock** [comment]
This has now been fixed in 09d7e9188de885972d33e58d35ae3ea7fa193718
