### ISSUE TITLE
Integra Live 1.7.1 server crashes on OS X 10.6.8

### ISSUE THREAD

**Issue by NiccoloGranieri** [BirminghamConservatoire/IntegraLive#998]
When Integra Live 1.7.1 is launched on an old Macbook Pro mounting OS X 10.6.8 a window pops up showing an error message: "Integra Live has stopped working! Integra Live's server has crashed"

On the same machine, Integra Live 1.6.4. runs smoothly.

MacBookPro1,1
OSX 10.6.8

**Comment by jamiebullock** [comment]
Hi @NiccoloGranieri this isn't actually a bug. As of 1.7.0 we only support OS X 10.7 or later. I think this is reasonable given 10.6 is now 6 years old. Our system requirements can be found here: http://integra.io/forum/discussion/1674/what-are-the-system-requirements-for-integra-live
